# docker-compose.yml
services:
  courtroom:
    build: .
    container_name: courtroom_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db  
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start"
    restart: unless-stopped
